/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOAD_H_RPCGEN
#define _LOAD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct param {
	int a;
	int b;
};
typedef struct param param;

struct student {
	char *nume;
	char *grupa;
};
typedef struct student student;

#define ADD_PROG 123456789
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_ADD 1
extern  int * get_add_1(param *, CLIENT *);
extern  int * get_add_1_svc(param *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_ADD 1
extern  int * get_add_1();
extern  int * get_add_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

#define CHECKPROG 0x31234567
#define CHECKVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GRADE 1
extern  char ** grade_1(student *, CLIENT *);
extern  char ** grade_1_svc(student *, struct svc_req *);
extern int checkprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GRADE 1
extern  char ** grade_1();
extern  char ** grade_1_svc();
extern int checkprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param (XDR *, param*);
extern  bool_t xdr_student (XDR *, student*);

#else /* K&R C */
extern bool_t xdr_param ();
extern bool_t xdr_student ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOAD_H_RPCGEN */
