/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "load.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
start_request_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		request start_request_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case START_REQUEST:
		_xdr_argument = (xdrproc_t) xdr_request;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) start_request_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
send_argument_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		request send_argument_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SEND_ARGUMENT:
		_xdr_argument = (xdrproc_t) xdr_request;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) send_argument_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (START_REQUEST_PROG, START_REQUEST_VERS);
	pmap_unset (SEND_ARGUMENT_PROG, SEND_ARGUMENT_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, START_REQUEST_PROG, START_REQUEST_VERS, start_request_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (START_REQUEST_PROG, START_REQUEST_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, SEND_ARGUMENT_PROG, SEND_ARGUMENT_VERS, send_argument_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SEND_ARGUMENT_PROG, SEND_ARGUMENT_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, START_REQUEST_PROG, START_REQUEST_VERS, start_request_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (START_REQUEST_PROG, START_REQUEST_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SEND_ARGUMENT_PROG, SEND_ARGUMENT_VERS, send_argument_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SEND_ARGUMENT_PROG, SEND_ARGUMENT_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
